### ISSUE TITLE
[CI] check run-onecc-build for dalgona

### ISSUE THREAD

**Issue by seanshpark** [Samsung/ONE#15484]
`run-onecc-build` workflow has
```
      # dalgona uses pybind11, but pybind11 cannot bind packages in virtualenv.
      # So we need to install packages for dalgona-test globally.
      - name: Install required packages
        run: |
          python3 -m pip install numpy h5py==3.11.0 flatbuffers==23.5.26
```
which canbe removed if virtualenv can be used.

let's check if it is possible.

**Comment by seanshpark** [comment]
check draft PR looks OK.
but fails with python3.10 upgraded draft PR.

https://github.com/Samsung/ONE/actions/runs/15312819639/job/43080927477?pr=15428

> fm-equalize: CalledProcessError: Command '['/__w/ONE/ONE/build/compiler/dalgona/dalgona', '--input_model', '/__w/ONE/ONE/build/compiler/fm-equalize-value-py-test/Conv2D_007.opt.circle', '--analysis', '/__w/ONE/ONE/build/compiler/fm-equalize/fmelib/DumpFMEParams.py', '--analysis_args', '/tmp/tmpjr4w7gpl/Conv2D_007.after.fme_patterns.json']' died with <Signals.SIGABRT: 6>.
Error raised while running the below command
/__w/ONE/ONE/build/compiler/dalgona/dalgona --input_model /__w/ONE/ONE/build/compiler/fm-equalize-value-py-test/Conv2D_007.opt.circle --analysis /__w/ONE/ONE/build/compiler/fm-equalize/fmelib/DumpFMEParams.py --analysis_args /tmp/tmpjr4w7gpl/Conv2D_007.after.fme_patterns.json
b'--input_data was not specified. Run with a random input.\n'
b"terminate called after throwing an instance of 'pybind11::error_already_set'\n  what():  ModuleNotFoundError: No module named 'numpy'\n\nAt:\n  /__w/ONE/ONE/build/compiler/fm-equalize/fmelib/DumpFMEParams.py(21): <module>\n  <frozen importlib._bootstrap>(241): _call_with_frames_removed\n  <frozen importlib._bootstrap_external>(883): exec_module\n  <frozen importlib._bootstrap>(703): _load_unlocked\n  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked\n  <frozen importlib._bootstrap>(1027): _find_and_load\n  <string>(5): <module>\n\n"

dlagona and virtualenv modified to work with python3.10
but current U20.04 CI installs with `python3 -m pip` command which will use default python3.8

**Comment by seanshpark** [comment]
local build test with focal Docker image without `numpy` in both 3.8 and 3.10 -> OK
um...

**Comment by seanshpark** [comment]
for CI, if numpy is both installed for 3.8, 3.10, it is OK
```yml
      - name: Install required packages (focal)
        if: matrix.ubuntu_code == 'focal'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install numpy==1.24.3 h5py==3.11.0 flatbuffers==23.5.26
          python3.10 -m pip install numpy==1.26.4 h5py==3.11.0 flatbuffers==23.5.26

      - name: Install required packages (jammy)
        if: matrix.ubuntu_code == 'jammy'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install numpy==1.26.4 h5py==3.11.0 flatbuffers==23.5.26
```
